/**
 * モデルエレメントタイプクラスヘッダファイル
 */

#ifndef RBAMODELELEMENTTYPE_HPP
#define RBAMODELELEMENTTYPE_HPP

namespace rba
{

enum class RBAModelElementType : std::uint8_t
{
  AllInstanceOfArea,
  AllInstanceOfViewContent,
  AllInstanceOfZone,
  AllInstanceOfSoundContent,
  Allocatable,
  AllocatedContent,
  AndOperator,
  Area,
  AreaSet,
  ArithmeticOperator,
  Constraint,
  ViewContent,
  ViewContentSet,
  ViewContentState,
  ContentValue,
  DisplayingContent,
  ExistsOperator,
  ForAllOperator,
  GetAllocatables,
  ActiveState,
  ActiveContents,
  GetContentsList,
  IfStatement,
  IfActionOperator,
  ImpliesOperator,
  IntegerValue,
  IsActive,
  IsDisplayed,
  IsEqualToOperator,
  IsGreaterThanEqualOperator,
  IsGreaterThanOperator,
  IsHidden,
  IsLowerThanEqualOperator,
  IsLowerThanOperator,
  IsVisible,
  LambdaContext,
  LambdaExpression,
  LetStatement,
  NotOperator,
  ObjectCompare,
  ObjectReference,
  MemberFeatureReference,
  OrOperator,
  PlusOperator,
  PreviousModifier,
  RuleObject,
  Scene,
  Property,
  SetExpression,
  SetOfOperator,
  SetOperator,
  ValueExpression,
  Variable,
  IsOn,
  Zone,
  ZoneSet,
  SoundContent,
  SoundContentSet,
  SoundContentState,
  IsAttenuated,
  IsOutputted,
  IsMuted,
  IsSounding,
  Rule,
  OnScene,
  OffScene,
  GetProperty,
  SetProperty,
  IntegerProperty,
  OutputtingSound,
  StateValue,
  HasBeenCanceled,
  HasBeenDisplayed,
  HasComeEarlier,
  HasComeLater,
  EventProcessing,
  MaxOperator,
  MinOperator,
  SelectOperator,
  SizeOperator,
  Undisplayed,
  IsTypeOfOperator,
  Displayed,
  None
};

}

#endif
