/**
 * RBAConstraintMap.hpp
 */

#ifndef RBACONSTRAINTMAP_HPP
#define RBACONSTRAINTMAP_HPP

namespace rba
{

enum class RBAConstraintMap : std::uint8_t
{
  CONTENT_ALLOCATE_CONSTRAINTS,
  HIDDEN_TRUE_CHECK_CONSTRAINTS,
  HIDDEN_FALSE_CHECK_CONSTRAINTS,
  ATTENUATE_TRUE_CHECK_CONSTRAINTS,
  ATTENUATE_FALSE_CHECK_CONSTRAINTS,
};

}

#endif
